### ISSUE TITLE
Some more examples

### ISSUE THREAD

**Issue by portalzine** [Hypfer/glance-clock#2]
As Glanceclock finally killed their service, I am looking into using the clock at least for some basic notifications.

I have not done much using protoBuffer in the past and started playing around with https://www.protobufpal.com/, without getting anywhere so far. 

I was able to connect to the clock and tried 
`gatttool --sec-level=high -b CLOCK_MAC -t random --char-write-req -a 0x001f -n 023000002203120141` 
with the correct MAC.

Tells me that it wrote to the characteristic, but see nothing happening on the clock itself.
Thanks for any additional help or recources you can provide. 

There are a bunch of us looking for ways to use the clock and not send it to the bin ;)

Thanks
Alex

**Comment by Hypfer** [comment]
Did you pair the clock to the host you're running that command on or did you just connect to the clock?
Because iirc (it has been a while), without pairing them, the clock just silently ignores any commands.

**Comment by portalzine** [comment]
Yes I paired it and connection works.

**Comment by portalzine** [comment]
Seems, that we will also be getting more info from the company itself soon. 
They seem to plan to share more  on Facebook this week (https://www.facebook.com/ClockGlance/).
Posted on XDA: https://xdaforums.com/t/glance-clock.4655490/post-89335420

**Comment by portalzine** [comment]
Works now after disconnecting and connecting the clock again. I think I am getting the hang of it :)
`gatttool --sec-level=high -b MAC -t random --char-write-req -a 0x001f -n 0230000022061204416c6578`
-> sends Alex ;)
or
`gatttool --sec-level=high -b EA:A8:80:3E:43:EA -t random --char-write-req -a 0x001f -n 0230000010001805220808001204416c6578` -> sends Alex with red Border   and no sound.

**Comment by portalzine** [comment]
Trying to get the digital watchface displaying again after the reconnect. Any pointer for that ?
Thanks for this so far and I will keep digging a bit more ...

**Comment by Hypfer** [comment]
The clock probably has no synced time and thus hid the digital clock among other stuff.
I'm using my glance clocks with my software that provides the service needed so that the clock can fetch the time

At some point, I threw some rough notes on how to set that up into an issue there:
https://github.com/Hypfer/Cybele/issues/12

However, those are just my notes so don't expect a finished product.


I'd also ask you to slow down please. I see that you're excited and all, but even though I reply quite quickly, you should not be doing the same. Take your time, think about the problem at hand. Try finding a solution using the docs that exist and if you struggle feel free to ask but please do so in a way that shows that time and thought went into the exchange.

If I say "it needs to be paired", you can't reply with "It is paired" less than 60s later.
You just can't throw the ball back that quickly. This ain't paid support

Thank you

**Comment by portalzine** [comment]
Thanks for taking the time to reply.  I am happy to be able to use the clock in some way again.
Already connected it via Node-Red to get most of my features back. 
Not expecting a finished product or anything else from you, just sharing my findings as many others are looking for a solution as well.
I know that this is not a support forum ;) and just a passion project of yours.
Thanks again for your time and I will try to internalize my excitement a bit more. 
Cheers
Alexander
